name = "solana-token-creator-api"
type = "javascript"
account_id = "your-account-id"
workers_dev = true
compatibility_date = "2023-01-01"

[build]
command = ""
[build.upload]
format = "service-worker"
