name = "coiner-dev"
type = "javascript"
account_id = "d427cccf1b3d465fd41dbc64650080dc"
workers_dev = true
compatibility_date = "2023-01-01"
main = "worker.js"

[build]
command = ""
[build.upload]
format = "service-worker"

routes = [
  { pattern = "coiner-dev.lusmodigital.workers.dev/api/token/create", zone_id = "efc9e1c0b00886e5f66cc6f23a076014" }
]