name = "solana-token-creator-api"
type = "javascript"
account_id = "d427cccf1b3d465fd41dbc64650080dc"
workers_dev = true
compatibility_date = "2023-01-01"
main = "worker.js"

[build]
command = ""
[build.upload]
format = "service-worker"
